CREATE TABLE `y_orders` (
  `id` mediumint(15) NOT NULL AUTO_INCREMENT,
  `orderSn` varchar(20) NOT NULL,
  `sortsn` varchar(20) DEFAULT NULL COMMENT '短订单号',
  `userId` mediumint(15) NOT NULL,
  `payType` varchar(120) NOT NULL,
  `deliveryMethod` tinyint(2) NOT NULL COMMENT '配送方式ID',
  `payStatus` tinyint(2) NOT NULL COMMENT '支付状态：1为未支付，2为已支付',
  `delStatus` tinyint(2) NOT NULL COMMENT '配送状态：1为未发货，2为已发货，3为已签收，4为拒收',
  `name` varchar(40) NOT NULL,
  `proviceId` varchar(40) NOT NULL,
  `cityId` varchar(40) NOT NULL,
  `countyId` varchar(40) NOT NULL,
  `townId` varchar(40) NOT NULL,
  `mobile` varchar(20) NOT NULL COMMENT '收货人手机',
  `address` varchar(120) NOT NULL COMMENT '街道/乡镇 之后的详细地址',
  `phone` varchar(20) NOT NULL COMMENT '收货人电话',
  `zipcode` varchar(100) NOT NULL COMMENT '收货信息 邮政编码',
  `amount` decimal(9,2) NOT NULL COMMENT '总金额(含运费、优惠和调价后的计算)',
  `goodsAmount` decimal(9,2) NOT NULL COMMENT '商品总额(不含任何费用)',
  `priceMod` decimal(9,2) NOT NULL COMMENT '调价',
  `coupon` decimal(9,2) NOT NULL DEFAULT '0.00' COMMENT '使用优惠券金额',
  `preferential` decimal(9,2) NOT NULL DEFAULT '0.00' COMMENT '用户优惠',
  `freight` decimal(9,2) NOT NULL COMMENT '配送费用',
  `weight` decimal(9,2) NOT NULL COMMENT '订单总重量',
  `sendTime` timestamp NULL DEFAULT NULL COMMENT '发货时间',
  `expressNo` varchar(40) NOT NULL COMMENT '物流快递单号',
  `payTime` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间',
  `completionTime` timestamp NULL DEFAULT NULL COMMENT '订单完成时间',
  `invoice` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否要发票',
  `usernote` varchar(200) NOT NULL COMMENT '用户备注',
  `note` varchar(200) NOT NULL COMMENT '管理员备注',
  `invoiceTitle` varchar(120) NOT NULL COMMENT '发标抬头',
  `insured` decimal(9,2) NOT NULL DEFAULT '0.00' COMMENT '保价费用 ',
  `point` int(11) NOT NULL COMMENT '获得积分',
  `type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '订单类型：1为普通订单，2为团购，3为限时抢购',
  `tradeSn` varchar(20) NOT NULL COMMENT '第三方支付交易号',
  `acceptTime` timestamp NULL DEFAULT NULL COMMENT '用户收货时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  KEY `id_2` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=77 DEFAULT CHARSET=utf8;
