CREATE TABLE `y_users` (
  `id` mediumint(15) NOT NULL AUTO_INCREMENT,
  `username` varchar(120) NOT NULL COMMENT '用户名',
  `password` varchar(80) NOT NULL COMMENT '密码',
  `wxopenid` varchar(200) DEFAULT NULL COMMENT '微信OPENID',
  `avatar` varchar(250) DEFAULT NULL COMMENT '头像',
  `question` varchar(120) DEFAULT NULL COMMENT '找回密码问题',
  `answer` varchar(120) DEFAULT NULL COMMENT '找回密码答案',
  `sex` tinyint(1) NOT NULL DEFAULT '1' COMMENT '性别',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `money` decimal(9,2) DEFAULT '0.00' COMMENT '资金余额',
  `frozenMoney` decimal(9,2) DEFAULT '0.00' COMMENT '冻结资金',
  `regTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `lastLogin` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT '最后一次登录时间',
  `curLogin` timestamp NULL DEFAULT '0000-00-00 00:00:00' COMMENT '当前登录时间',
  `nickname` varchar(120) DEFAULT NULL COMMENT '昵称',
  `mobile` varchar(20) NOT NULL COMMENT '手机号码',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态',
  `payPoints` int(11) DEFAULT '0' COMMENT '积分总数',
  `usepayPoints` int(11) NOT NULL DEFAULT '0' COMMENT '已兑换积分',
  `pointslog` varchar(255) DEFAULT NULL COMMENT '最近一次积分增加记录',
  `userRank` int(11) DEFAULT '0' COMMENT '用户等级',
  `email` varchar(180) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `mobile` (`mobile`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;
